### ISSUE TITLE
simulation t_step not as defined in template_simulator.py

### ISSUE THREAD

**Issue by xholcaravan** [do-mpc/do-mpc#100]
Inside template_mpc.py I define (inside setup_mpc) the 't_step': 10. I.e. the controller actuates every 10 seconds. I use 'n_horizon': 100,
Inside template_simulator.py I define (inside params_simulator) the 't_step': 1 second
In main.py i run: for k in range(1000):

This is expected to run a simulation for 1000 seconds but what I have as output is 1000 instances with time_step 10, i.e. i have a simulation of 10000 seconds.

Installed do_mpc via pip
Using own code departing from your examples.

**Comment by alexandru-tc** [comment]
Hello @xholcaravan, 
thanks for your question! What you are describing is in fact a very realistic behavior, but one we do not fully support yet in do-mpc. At the moment we assume that the controller and the simulator are working with the same sampling time, whatever that might be. And it is the definition of the controller that governs the simulation. That is the explanation. A more "real-time" like implementation of do-mpc, where the simulator, estimator and controller are fully independent and can operate on separate timelines and with individual sampling rates is under development as a real-time extension ( or asynchronous do-mpc) formulation, but it is not yet part of the current release. 

If you really want to get simulation results every 1 second and so something special to them, you could "hack"  the main file of do-mpc by going into the main loop and calling the simulator yourself ten times before resuming the normal execution, i.e. new measurement and new optimization run. But I'd really think about why doing that makes sense. Keep in mind that you would have to override the internal sampling time of the simulator. How involved do you want to get with the code? What are you actually trying to replicate with your sampling times?   

Cheers,
Alex

**Comment by 4flixt** [comment]
Hi @xholcaravan,

the way to solve your problem is simple:

```python
for k in range(100):
   # 100 inputs with a timestep of 10 seconds
    u0 = mpc.make_step(x0)
    for i in range(10):
       # use the same input for 10 simulation steps with a timestep of 1 second 
       x0 = simulator.make_step(u0)
```
Probably, you want to investigate the ``simulator.data`` object in the end to evaluate your control performance.

Best,
4flixt

**Comment by xholcaravan** [comment]
Hello @alexandru-tc and @4flixt 

Thank you for your prompt answers!

I will be applying MPC to frequency control in power systems. It is indeed necessary to simulate the system behaviour with a much smaller time-step than the controller actuation, because transients matter a lot in this case.
@4flixt suggestion is indeed a simple way of handling this!

Cheers,
xholcaravan

**Comment by DystopianLphant** [comment]
If I understand correctly you are mixing the t_step of the controller and the execution time: the t_step of the mpc is used for the internal sampling and later computations, whilst the execution time is defined in the execution loop.
for example: I need a simulation with t_step = 0.01s and a controller that runs every 0.1 with an internal t_step of 0.01s

`for i in range(3000):
    if i%10 == 0:
        u0 = mpc.make_step(x0)
    x0 = simulator.make_step(u0)
`
so after setting the mentioned t_step I'm making the controller run every 10 simulation steps using the modulo operator and an if statement. the simulation runs for range*t_step = 3000*0.01 = 30 seconds with 300 control runs

**Comment by 4flixt** [comment]
@DystopianLphant answer also works! I am closing this now.
