### ISSUE TITLE
adding a known disturbance to the problem

### ISSUE THREAD

**Issue by afatsum93** [do-mpc/do-mpc#102]
Hello, 

I am formulating an mpc formulation to a vehicle trajectory optimization problem where my model equations consist of the future trajectory curvature as an uncontrollable, but known input. 

How can I implement the curvature input vector to my problem horizon?

Thanks for the nice library!

**Comment by 4flixt** [comment]
Dear afatsum93,

apologies for my late reply.
Inputs to the system that are unknown but controllable are considered "time varying parameters" (``tvp``)  in **do-mpc**. The must be introduced as such in the model.
The controller needs to know the predicted future sequence of these values and the simulator needs to know the current value at each iteration. You will find more information [here](https://www.do-mpc.com/en/latest/FAQ.html#time-varying-parameters).

Best,
4flixt
