### ISSUE TITLE
a posteriori cost computation once the simulation is finished

### ISSUE THREAD

**Issue by DystopianLphant** [do-mpc/do-mpc#103]
**Is your feature request related to a problem? Please describe.**
I'm in the situation of evaluating the behaviour of different configurations by means of the total control cost, expressed as the integral of the square of the control action(s). 
Is there already a way to it? Otherwise I would create my own and maybe share it to implemented, tough I'm just a pragmatic non-IT engineer, whose knowledge isn't enough to make a commit without help.

p.s. : what about settling time? I would do it too

**Comment by 4flixt** [comment]
hi @DystopianLphant,

with "a posteriori", I assume you mean the closed-loop cost? That would be computed from the true (simulated) system response after recursively applying the MPC inputs and result in a single value. That is currently not implemented but should be a simple addition. It could be a method of the ``MPCData`` object and would simply need to evaluate the [cost function](https://github.com/do-mpc/do-mpc/blob/004365c1ceb6b419af8f6af1035f11e6031b2f21/do_mpc/controller.py#L490) (already exists as a function in the ``MPC`` class) with all the currently available recorded data. 

Another interesting information that is also currently not stored is the open-loop cost calculated at each time-step. Basically, the cost of the individual MPC problems. This isn't stored either which should probably also be changed. 

Thank you very much for offering help with the coding. Feel free to fork the codebase and do either of these implementations and then submit a pull request for my review.
Alternatively, I suggest you temporary just implement these features for yourself. The [cost function](https://github.com/do-mpc/do-mpc/blob/004365c1ceb6b419af8f6af1035f11e6031b2f21/do_mpc/controller.py#L490) pointed out above should be all you need.

I will also add both features as individual issues and will hopefully soon have time to work on them. 

Best,
4flixt

**Comment by 4flixt** [comment]
Actually, I realized it doesn't make sense to add the computation of the closed-loop cost to the ``MPCData`` object. In practice, you care about the closed-loop cost achieved from the "real" system (in most cases our simulator object). 

So I guess the best way really is to manually use the cost function defined in the MPC object and evaluate it with data from the simulator.

**Comment by DystopianLphant** [comment]
I meant the control cost, which is usually defined as the sum over inputs of the integral over time of squared input values, it took me 4 lines of code, my bad considering it so important.
The mean of this was to evaluate the performances of different controllers.
other than that the settling time is more challenging and would still require visual inspection to avoid jumping through hoops in the code.
