### ISSUE TITLE
Typo of setup_model function in documentation

### ISSUE THREAD

**Issue by isakhammer** [do-mpc/do-mpc#108]
Regarding the documentation on your [do-mpc](do-mpc.com) homepage.

**Link to page / section of the issue** 
https://www.do-mpc.com/en/v4.0.0-beta/api/do_mpc.model.Model.html

![image](https://user-images.githubusercontent.com/43385748/104167206-44703380-53fc-11eb-9a89-ce9c1a2f409f.png)

**What is wrong / missing?**
The documentation is using a function `model.setup_model()`, which does not exist. 

**How could it be improved / what should be added?**
I looked up in the source code [here](https://github.com/do-mpc/do-mpc/blob/master/do_mpc/model.py) at line 954 and realized  the correct function name is `model.setup()`.

**Comment by 4flixt** [comment]
Thank you Isak! That is still a relict from some older version. Will change it ASAP :)
