### ISSUE TITLE
Neural Network MPC

### ISSUE THREAD

**Issue by prajwal210798** [do-mpc/do-mpc#110]
Hello Everyone,
I want to use NN as a  prediction model in MPC, I have checked CASADI and there you have to create a call back function to work with  TensorFlow  based  model in CASADI.

I want to know that if do-mpc provides an easier and faster approach towards this / or some one have implemented NN-MPC with do-mpc?

**Comment by 4flixt** [comment]
Dear Prajwal,

we are currently working on this feature and have been implementing NN as system models with do-mpc in the past. We hope to be able to make this feature generally available for do-mpc in the near future. Stay tuned for updates!

Best
4flixt

**Comment by prajwal210798** [comment]
Oh I see,  could you tell me a little bit like how can we integrate nn or any general tensorflow model with do-mpc?

**Comment by 4flixt** [comment]
Hi prajwal,

so the most straightforward thing to do is just to retrieve the weights and structure of your tensorflow model and reimplement this using CasADi. This method will also lead to the best performance as it is now a native CasADi implementation. If you are using standarf feed-forward NN it really isn't too difficult. 

Hope this helps.

Best,
4flixt

**Comment by prajwal210798** [comment]
Thanks , I am able to implement nn-mpc , hoping to see this feature in do-mpc soon.

**Comment by 4flixt** [comment]
Hi @davidzanger,

there are indeed updates. We are soon going to release a new version of do-mpc with an (experimental) feature to convert neural networks from the universal ONNX standard to the do-mpc notation. 

You can read more about the feature on the [develop branch of do-mpc](https://www.do-mpc.com/en/develop/api/do_mpc.sysid.onnxconversion.ONNXConversion.html#do_mpc.sysid.onnxconversion.ONNXConversion).

Best,
4flixt

**Comment by sumedhs-1995** [comment]
> Thanks , I am able to implement nn-mpc , hoping to see this feature in do-mpc soon.

@prajwalthakur could you post the code for reference on GitHub if possible, I will be sure to cite it.

Best Regards,
Sumedh
