### ISSUE TITLE
Add Reference Input (r)

### ISSUE THREAD

**Issue by rballachay** [do-mpc/do-mpc#111]
Hi Everyone, 

I am working on an undergraduate thesis project which requires me to identify systems using neural networks under closed-loop control. One of the methods for identification I outlined in my proposal requires the addition of a reference input r to the system in addition to the inputs under direct MPC control (u). In my case, this reference input would have a PRBS structure. Is there any easy way to implement this? It would be greatly appreciated.

Thanks,

Riley

If you are wondering what I am referring to by 'reference input', I have attached a paper below which explains. 

[CLOSED-LOOP SYSTEM IDENTIFICATION OF A MlMO PLANT CONTROLLED BY A MPC CONTROLLER .pdf](https://github.com/do-mpc/do-mpc/files/5900368/CLOSED-LOOP.SYSTEM.IDENTIFICATION.OF.A.MlMO.PLANT.CONTROLLED.BY.A.MPC.CONTROLLER.pdf)

**Comment by 4flixt** [comment]
Hi @rballachay ,

I just saw you closed that and hopefully you found the answer to you problem (I mean to reply later today). 
In case you didn't find the answer, have a look at this [feature](https://www.do-mpc.com/en/latest/FAQ.html#time-varying-parameters).

Best
4flixt
