### ISSUE TITLE
changed behaviour of matrices made of numpy arrays containing variables 

### ISSUE THREAD

**Issue by DavidePatria** [do-mpc/do-mpc#114]
I have a few different script, also different versions of the same model, that use the following

`euler_ang` = model.set_variable(var_type='_x', var_name='euler_ang', shape=(3,1))

```
matrice_rotazione = np.array([[cos(euler_ang[1])*cos(euler_ang[2]),\
                               sin(euler_ang[1])*sin(euler_ang[0])*cos(euler_ang[2])-sin(euler_ang[2])*cos(euler_ang[0]),\
                               cos(euler_ang[2])*sin(euler_ang[1])*cos(euler_ang[0]) + sin(euler_ang[0])*sin(euler_ang[2])],\
                               [sin(euler_ang[2])*cos(euler_ang[1]),\
                               (sin(euler_ang[1])*sin(euler_ang[0])*sin(euler_ang[2])+cos(euler_ang[2])*cos(euler_ang[0])),\
                               sin(euler_ang[1])*cos(euler_ang[0])*sin(euler_ang[2]) - sin(euler_ang[0])*cos(euler_ang[2])],\
                               [-sin(euler_ang[0]),\
                               cos(euler_ang[1])*sin(euler_ang[0]),\
                               cos(euler_ang[1])*cos(euler_ang[0])]])
```

where matrice_rotazione means rotation matrix (simple one). I built such matrix using np.array. This matrix is later used to rotate a vector in the expression

`v_i = model.set_expression('v_i', matrice_rotazione@v_b)

everything used to work fine. I put apart the script for some time and reopened them today, but I get this error

```
**Exception:** Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.
```
which makes sense, but it never happened before. It might be given by an update from the system repos, since I didn't touch pip, but I didn't investigate too much.
Given that the used solution was quite fragile and not the intended behaviour I'm better changing the expression of this once for all to get it consistent throughout future updates and uses.

Is it possible to define a matrix using set_expression and later multiply it to a vector in an equivalent way to v_b@matrix ? 
Or am I better going directly for the expanded matrix product hand expanded?
I thought that matrix_rotation might be defined as '_aux' and that a method (my taxonomy might inexact) like vertcat could exist that creates a matrix rather then a stack of expressions.

Adding a simple example involving something like the case above might solve many problems, given that the casadi doc hasn't been helpful,  for me at least.

thank you, and my strange aeroplane is being controlled quite amazingly by this library, so compliments.

**Comment by DavidePatria** [comment]
worth mentioning that downgrading numpy to 1.19.0 makes te aforementioned abysmal abuse of notation function as before.
I'm sticking for this until the end of this project, but I'm still willing to know the proper way of doing it

**Comment by 4flixt** [comment]
Hi Davide,

the preferred way to deal with this situation is to import the casadi toolbox (one which do-mpc is based on):
```
import casadi as cas
```
and use the functions `vertcat` or `horzcat` for vertical / horizontal concatenation. 
You might need to nest `vertcat` and `horzcat` to create a matrix.

Best
4flixt

**Comment by DavidePatria** [comment]
I guess using vertcat and horcat still wouldn't allow for matrix product

**Comment by 4flixt** [comment]
Matrices and vectors created with `vertcat` or `horzcat` (or by defining matrix or vector variables directly) allow matrix multiplication. You can use the `@` operator or with the ``mtimes`` function from casadi. I prefer using `@` because it is the exact same syntax as with numpy then.

**Comment by DavidePatria** [comment]
Thank you, I couldn't find any useful documentation regarding this.
