### ISSUE TITLE
weird results from discrete time model

### ISSUE THREAD

**Issue by sdaronco** [do-mpc/do-mpc#118]
**Describe the bug**
I implemented a very simple discrete time model to control the water level of two tanks. I get very weird results:
 state bounds get violated ant inputs then saturate to their maximum and minimum value. I cannot understand if I have done something wrong or if there is a bug somewhere. The code is rather simple, I would be glad if  you could have a quick look.

**Which version of do-mpc are using and how did you obtain it?**
- installed with pip

**Are you running our examples or your own code?**
- my own code

**Which system are you working on?**
- Linux

**Additional context**
I attach the code
[tanks.txt](https://github.com/do-mpc/do-mpc/files/6087291/tanks.txt)

**Comment by sdaronco** [comment]
sorry I think this is related to issue 89 (https://github.com/do-mpc/do-mpc/issues/89.) After I added  'state_discretization': 'discrete' in the controller parameters it worked fine.

**Comment by 4flixt** [comment]
Great to hear you could fix it yourself. I definitely need to work on #89 soon.

Best
4flixt
