### ISSUE TITLE
Add a generator to autocomplete template_mode.py

### ISSUE THREAD

**Issue by sergiolucia** [do-mpc/do-mpc#13]
For the initial condition, the constraints one has to repeat many times the names of the variables, concatenate the variables on vectors etc.... this could be pre-completed automatically and then the user only has to replace some numbers where applicable

**Comment by 4flixt** [comment]
**do-mpc** v4.0.0 adresses this issue directly and has a much simpler configuration of model and optimizer with many default values and autocompletions
