### ISSUE TITLE
Slow drift while using soft constraint

### ISSUE THREAD

**Issue by sakthiinfy** [do-mpc/do-mpc#19]
Using only one decision variable (softening) for all the time points causes slow drift while using a standard NMPC. This can be avoided by having one decision variable for each time points.

**Comment by sergiolucia** [comment]
Hi,
for which example is this happening?
I already implemented your suggestion for some examples so it is not a big effort to change it. I just wanted to know for which example this plays an important role, since this could considerably increase the number of decision variables.

**Comment by sakthiinfy** [comment]
Hi Sergio,

I was using this Klatt Engell model. The drift is small if you dont consider any plant model mismatch but if you consider any structural plant model mismatch as in (Handling Structural Plant-model Mismatch via Multi-stage Nonlinear
Model Predictive Control) the drift is significant. 

The number of increase in decision variable is (prediction_horizon - 1)*number_of_constraints. I think this is not that significant when compared to the overall size of the problem. If you still feel that this too much we could separate the firs stage in the prediction horizon from the rest by having an increase of 2*number_of_constraints of decision variables.

I too changed it but it would be difficult for others especially if they dont know how setup_nlp is implemented. I thought that this could be modified in the next release.

Regards
Sakthi

**Comment by sergiolucia** [comment]
Hi Sakthi,

yes, probably is better to put it as default as you suggested. Few people will be able to modify it. I will change it for the next release.

Thanks!

Sergio
