### ISSUE TITLE
Embed sensitivity analysis in main configuration 

### ISSUE THREAD

**Issue by BrunoMorabito** [do-mpc/do-mpc#20]
Sensitivity is running by setting another configuration. That means it is considered as completely another model. This causes loss of efficiency because the same variable, such as states, control variables etc, must be saved twice.

The solution would be using the model with symbolic parameters in the main configuration. This would permit to run the sensitivity analysis together with the model in  all in one configuration.

**Comment by 4flixt** [comment]
**do-mpc** version 4.0.0 is a complete overhaul of the previous generation. This issue refers to the previous generation and is therefore closed. If you have feedback and feature suggestions for the new version, please
