### ISSUE TITLE
Error applying MHE in absence of measurement noise

### ISSUE THREAD

**Issue by dsdhms** [do-mpc/do-mpc#214]
I am trying to estimate parameters using MHE without measurement noise.

I receive an error while using the MHE example file if there were no measurement noise. The error is shared in the screenshot below. I have also attached the variation of the example file, I am using.

**Verison**: do-mpc  4.3.1
**Installation**: pip

Example?: Running a variations of the MHE example:
**MHE example, without any measurement noise**: The `meas_noise` attribute was set to `False` and _P_v_ matrix was removed from the attributes of `mhe.set_default_objective` as `mhe.set_default_objective(P_x, P_p= P_p)`

Screenshot of the error:
![image](https://user-images.githubusercontent.com/84672836/148196734-e3ef363c-0f9c-484a-95c0-032dbc47fe6f.png)
[mhe_example_no_meas_noise.zip](https://github.com/do-mpc/do-mpc/files/7813836/mhe_example_no_meas_noise.zip)

Operating system: Windows 11

**Additional context**
I would be happy to provide any further information if required. Thanks in advance.

**Comment by cvoky** [comment]
I have encountered the same issue. Is there a workaround for this? Thanks.

**Comment by 4flixt** [comment]
Can you update do-mpc and test again? It should be fixed now.

**Comment by cvoky** [comment]
Thanks for the update, unfortunately it doesn't help. I think assert for [`stage_cost`](https://github.com/do-mpc/do-mpc/blob/69c11c52bc6ba8253faf0b33370cc90a239f0938/do_mpc/estimator.py#L705) in `mhe.set_objective()` will stop me either. If I change initial setup of [`stage_cost`](https://github.com/do-mpc/do-mpc/blob/69c11c52bc6ba8253faf0b33370cc90a239f0938/do_mpc/estimator.py#L824) in `mhe.set_default_objective()` to `SX` format as `SX(0)` your update starts working, thanks.

**Comment by 4flixt** [comment]
I am so sorry -  I confused this with #215 (which i fixed yesterday). This one is still open. I hope I'll have to time to tackle the problem this week.
