### ISSUE TITLE
Error applying MHE for only state (and no parameters) estimation

### ISSUE THREAD

**Issue by dsdhms** [do-mpc/do-mpc#215]
I am trying to estimate only the state(s) (and no parameters) using MHE.

There seems to be The error is shared in the screenshot below. I have also attached the variation of the example file, I am using.

**Verison**: do-mpc  4.3.1
**Installation**: pip

Example?: Running a variation of the MHE example:
**MHE example, NO parameter estimation &  only state estimation**: 
1. While configuring the MHE  `mhe = do_mpc.estimator.MHE(model, ['Theta_1'])` was changed to `mhe = do_mpc.estimator.MHE(model, [])`
2. While defining the weighting matrices `P_p` was removed as: `mhe.set_default_objective(P_x, P_v)`

Screenshot of the error:
![image](https://user-images.githubusercontent.com/84672836/148198315-af464351-3108-4440-af55-8a24c962d5b1.png)

[mhe_example_only_state_est.zip](https://github.com/do-mpc/do-mpc/files/7814001/mhe_example_only_state_est.zip)

Operating system: Windows 11

**Additional context**
I would be happy to provide any further information if required. Thanks in advance.

**Comment by ronmarti** [comment]
I still encounter the issue in version 4.3.5.:
```error
...
File "C:\Users\marti\AppData\Local\pypoetry\Cache\virtualenvs\mpc-oven-1B0jcswj-py3.9\lib\site-packages\do_mpc\estimator.py", line 263, in __init__ p_cat = substitute(p_cat, _p, vertcat(*_p_subs))
File "C:\Users\marti\AppData\Local\pypoetry\Cache\virtualenvs\mpc-oven-1B0jcswj-py3.9\lib\site-packages\casadi\casadi.py", line 22160, in substitute
RuntimeError: .../casadi/core/sx_instantiator.cpp:460: Sparsities of v and vdef must match. Got v: 0x1 and vdef: 0x0.
```
I found out that when no parameter in model is declared, the variable `_p` contains name `'default'` and the casadi's `vertcat` doesn't cope with that well.
I was able to make a naive workaround in file `estimator.py`, in class `MHE` in `__init__` at line 263:

```python
if len(_p_subs) > 1:  # Not only 'default' in the list
    p_cat = substitute(p_cat, _p, vertcat(*_p_subs))
```
I have no idea what else this may have corrupted.

**Comment by maqifrnswa** [comment]
I just hit into this bug too with do-mpc 4.4.0. I too see the 'default' in the list. the work around in https://github.com/do-mpc/do-mpc/issues/215#issuecomment-1156650417 fixed it for me too.
