### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Neotriple** [do-mpc/do-mpc#23]
Hi all,

I recently stumbled upon your software and was attempting to run the example in

/do-mpc/examples/CSTR

However, when I type in "python do-mpc.py"

I receive the following error:

Traceback (most recent call last):
  File "do-mpc.py", line 59, in <module>
    simulator_1 = template_simulator.simulator(model_1)
  File "/Network/Servers/duerer/Volumes/duerer/paarth/do-mpc/examples/CSTR/template_simulator.py", line 76, in simulator
    simulator_1 = core_do_mpc.simulator(model, simulator_dict)
  File "../../code/core_do_mpc.py", line 95, in __init__
    simulator_do_mpc = integrator("simulator", param_dict["integration_tool"], dae,  opts)
  File "/usr/local/lib/python2.7/dist-packages/casadi/casadi.py", line 14327, in integrator
    return _casadi.integrator(*args)
RuntimeError: .../casadi/core/options.cpp:246: Unknown option: exact_jacobian

Any suggestions? Is it perhaps because this version does not work with the latest version of CASadi? 

*Edit*

exact_jacobian seems to be a deprecated function after casadi was refactored a while ago as per this post:

https://groups.google.com/forum/#!topic/casadi-users/xvsFNFjtVJ0

In order to fix this, after the line:

opts = param_dict["integrator_opts"]

type in:

del opts["exact_jacobian"]

**Comment by sergiolucia** [comment]
Hi Neotriple,

Even though you just closed the thread. Yes, the reason is the new CasADi version. The easiest solution is if you install CasADi 3.0.
I am preparing a new version of do-mpc that will work with the newest version of CasADi, but I still need around 4 weeks to finish it.

Best regards,

Sergio
