### ISSUE TITLE
Unable to set a custom `_tvp` function because of incorrect template index

### ISSUE THREAD

**Issue by daqwes** [do-mpc/do-mpc#247]
**Describe the bug**
I am trying to set a custom `_tvp` function using `set_tvp_fun`. After getting the template using `mpc.get_tvp_template` (`mpc` being a `do_mpc.controller.MPC` object), I try to set the `_tvp` values, however it is out of index, and only `default` and my other parameters are available. The same happens if I only set my particular parameters, only this time at runtime when my custom function is called. **Relevant code snippet:**

```
tvp_temp_2 = simulator.get_tvp_template()
tvp_temp_2['_tvp', :] = np.array([0,0])
# Or tvp_temp_2['vwind"] = np.array([0])
#    tvp_temp_2['phi'] = np.array([0])
def tvp_fun_simulator(t_now):
    return tvp_temp_2

simulator.set_tvp_fun(tvp_fun_mpc)
```
(same for mpc object)
**Error :**
```
File "C:\Users\danie\miniconda3\envs\DS\lib\site-packages\casadi\tools\structure3.py", line 344, in traverseByPowerIndex
  return self.dict[p].traverseByPowerIndex(
File "C:\Users\danie\miniconda3\envs\DS\lib\site-packages\casadi\tools\structure3.py", line 125, in __getitem__
  raise Exception("Unknown keyword '%s'. Available entries: %s" % (k,str(list(self.keys()))))
Exception: Unknown keyword '_tvp'. Available entries: ['default', 'vwind', 'phi']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File ".\main.py", line 152, in <module>
  main()
File ".\main.py", line 114, in main
  tvp_temp_2['_tvp', :] = np.array([0,0])
File "C:\Users\danie\miniconda3\envs\DS\lib\site-packages\casadi\tools\structure3.py", line 118, in proper
  return f(self,mbt,*args)
File "C:\Users\danie\miniconda3\envs\DS\lib\site-packages\casadi\tools\structure3.py", line 634, in __setitem__
  return self.struct.traverseByPowerIndex(powerIndex,dispatcher=
File "C:\Users\danie\miniconda3\envs\DS\lib\site-packages\casadi\tools\structure3.py", line 430, in traverseByPowerIndex
  raise Exception("Error occured in struct context with powerIndex %s, at canonicalIndex %s" % (str(powerIndex),str(canonicalIndex))) from e
Exception: Error occured in struct context with powerIndex ('_tvp', slice(None, None, None)), at canonicalIndex ()
```

**Which version of do-mpc are using and how did you obtain it?**
Version 4.3.3, installed using pip

**Are you running our examples or your own code?**
- The example is very similar to what is presented on your [website](https://www.do-mpc.com/en/latest/api/do_mpc.controller.MPC.set_tvp_fun.html)

**Which system are you working on?**
 - Windows

**Comment by 4flixt** [comment]
The ``tvp`` objects behave differently for MPC and Simulator. The MPC controller requires a sequence of ``tvp`` values over the entire horizon (to make predictions) and the simulator just needs the current value.

Therefore you must read about [simulator.set_tvp_fun](https://www.do-mpc.com/en/latest/api/do_mpc.simulator.Simulator.set_tvp_fun.html)
