### ISSUE TITLE
Cost Function

### ISSUE THREAD

**Issue by hxlee309** [do-mpc/do-mpc#27]
What's the difference between Lagrange term and Mayer term in the cost function?

**Comment by sergiolucia** [comment]
The Lagrangian term is the stage cost (which is added at each time step) and the Mayer term is the terminal cost only added at the final prediction step

**Comment by jmrssc** [comment]
Hello @sergiolucia! Just to check what you answered to @hxlee309, in [this](https://imgur.com/a/LNvfwrq) OCP, the mayer term would be the F(.), right?

**Comment by sergiolucia** [comment]
Yes. That is correct. Good luck with your project!

**Comment by jmrssc** [comment]
Thank you so much for your answer! And thanks for this tool!
