### ISSUE TITLE
Substitute Simulator with Real system

### ISSUE THREAD

**Issue by smababou** [do-mpc/do-mpc#29]
- If I'm using do_mpc with my system, How would I use real variables of my system to substitute the simulator?

- Here an example for my system which runs perfectly with the simulator:
[mobile_robot.zip](https://github.com/do-mpc/do-mpc/files/2991414/mobile_robot.zip)

- I would like to use do_mpc with my real robot. (I can measure all my states)

**Comment by alexandru-tc** [comment]
Dear Abdulrahman,

thanks for your question. If I remember correctly, you are an A&R student
working on your internship now? In any case, what I mean to say is that if
you are in Dortmund, we could easily meet to discus your application.

In short, replacing the simulation with the real system would require you
implementing some sort of interface, which would substitute the simulation
module in do-mpc. In orther words, you need some code that would be called
by the function run_simulation() and that would return the states of the
system (i.e the robot). That might be more or less easy to do, depending on
what kind of communication you are using.

I can also tell you that, for our process systems where we are working with
do-mpc, we are currently developing a solution based on an industrial
standard for communication called OPC UA. A basic module for do-mpc will be
also made available during the month of April. I still suggest that you
contact me separately to discuss the topic.

All the best,
Alexandru

**Comment by smababou** [comment]
Thank you for your prompt reply. 
I'm currently in Dortmund, I will contact you by email, to set a meeting to discuss my application.
The development sounds great, and thanks for the great work.

Thanks and Best Regards
Abdulrahman

**Comment by 4flixt** [comment]
Dear Abdulrahman,

we are currently testing **do-mpc** v4.0.0-beta which adresses this issue in a straight-forward fashion.
If this is still an open question, please see our documentation on [do-mpc.com](www.do-mpc.com),
and see the examples.

Best,
Felix
