### ISSUE TITLE
 P_ksb = P[b + branch_offset[k][s]] is showing index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by biswa007753** [do-mpc/do-mpc#31]
On executing a HEV model code the above error is showing is there a solution to it

**Comment by 4flixt** [comment]
**do-mpc** version 4.0.0 is a complete overhaul of the previous generation. This issue refers to the previous generation and is therefore closed. If the problem persists with the current generation please raise a new issue.
