### ISSUE TITLE
Heads up: casadi Integrator option "tf" is deprecated from casadi 3.6.0

### ISSUE THREAD

**Issue by Filippo-Tamagnini** [do-mpc/do-mpc#364]
Call to casadi integrator in do-mpc Simulator.setup, see line 193 of simulator.py, contain an option that is deprecated from casadi 3.6.0

It currently prints this warning:
CasADi - 2023-04-14 10:30:21 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:495]

It can be solved quite effortlessly by passing t0 and tf arguments to the integrator call, e.g.:
```
from casadi import *

x = SX.sym("x")
dx = -x
ode_dict = {"x": x, "ode": dx}
old_opts = {"t0":0, "tf": 10}

print("Deprecated")
I = integrator("test", "cvodes", ode_dict, old_opts)
print(I(x0 = 1)["xf"])

print("3.6.0 compliant")
I = integrator("test", "cvodes", ode_dict, old_opts["t0"], old_opts["tf"])
print(I(x0 = 1)["xf"])
```
not quite sure however if this works with casadi < 3.6.0

See casadi changelog https://web.casadi.org/get/

**Comment by 4flixt** [comment]
Thank you for the heads up :) Will update it in the next release.
