### ISSUE TITLE
Doc: Spelling

### ISSUE THREAD

**Issue by ramirlab** [do-mpc/do-mpc#41]
~~"to be used"~~
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/do_mpc/model.py#L164

~~"separately"~~
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/do_mpc/model.py#L206

~~I think the second ``lterm`` should be ``mterm``~~
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/do_mpc/controller.py#L213

~~"chosen"~~. Also ~~"optimizer"~~
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/getting_started.ipynb#L595

~~"numerical"~~
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/getting_started.ipynb#L666

~~"supresses"~~
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/getting_started.ipynb#L806

~~"supress"~~
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/getting_started.ipynb#L1068

**Comment by ramirlab** [comment]
Some additional mistakes I have found in the MHE getting started documentation:

"Typically"
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/mhe_example.ipynb#L90

"separately"
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/mhe_example.ipynb#L92

"such" (and closing the parenthesis after ``c``)
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/mhe_example.ipynb#L114

"initialize"
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/mhe_example.ipynb#L382

"numerical"
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/mhe_example.ipynb#L436

possibility?
https://github.com/do-mpc/do-mpc/blob/933038f730ecf87ce8b802a35dc367b5a9cf350c/documentation/source/mhe_example.ipynb#L762

**Comment by 4flixt** [comment]
Fixed in commit 72cdbc603f17511103e247affb76f8189e093b96
and in commit 80eae89b105eda8f04454a3d223f7a7b6ce10f23
