### ISSUE TITLE
Default abstol and reltol options in Simulator class prevent use of integrators such as collocation or rk4.

### ISSUE THREAD

**Issue by DeanBrandner** [do-mpc/do-mpc#415]
In the ``Simulator`` class, the options passed to the integration tool have ``abstol`` and ``reltol`` as default fields (see [here](https://github.com/do-mpc/do-mpc/blob/6c8882a510444aba99bed263b89a04709db29b82/do_mpc/simulator.py#L240C15-L240C15)). However, this works for cvodes and idas but not for collocation (see [here ](https://web.casadi.org/python-api/#integrator) at 1. collocation) and most likely also not for rk4 because they do not have these options.

**Proposed solution:**
Just check the integration tool and make the defaults case sensitive. Provide some default options for cvodes and idas, but also for collocation and rk4.

**Comment by Mrfeli01** [comment]
Hi Dean, this should be fixed in the latest released (at least for collocation).
Best
Mrfeli01
