### ISSUE TITLE
Trouble Setting TVP Variables in do_mpc

### ISSUE THREAD

**Issue by AlirezaYaghoubi** [do-mpc/do-mpc#424]
Problem:
I am encountering difficulties when trying to set Time-Varying Parameters (TVP) in my do_mpc setup. The issue seems to be related to accessing and assigning values to the TVP variables correctly.

Context:
I have a control problem that involves manipulating TVP variables during my MPC optimization. I have followed the documentation and community discussions but have encountered a persistent error related to powerIndex slicing.

Relevant Code:
# Relevant portion of the code
tvp_index = self.tvp_template["_tvp"].find('weaSta_reaWeaTDryBul_y')
self.tvp_template["_tvp", 0, tvp_index] = loaded_data

Error Message:
The error message suggests an issue with powerIndex slicing, specifically for the TVP variable 'weaSta_reaWeaTDryBul_y'. I have tried various approaches, but the problem persists.

Main Issue:
In my simulation, I noticed that the graph after the running the simulator correctly displays all tvp variables. However, the results related to states variables (reaTZon_y, and T_e) are consistently zero, with minimal movement at the end of the simulation period.

On the other hand, the prediction graph displays correct results for states and control variables (reaTZon_y, and T_e) based on my cost function. However, the input variables appear to be constant throughout the simulation.

Expected Outcome:
I expect that setting TVP values should work smoothly without encountering powerIndex slicing errors, and the simulation should produce accurate results for both input and output variables.

Request for Assistance:
I would appreciate any guidance or insights from the do_mpc community on the correct way to set TVP values in my specific scenario. Additionally, I am seeking assistance in resolving the discrepancy in results between input and output variables in my simulation.

Additional Information:
I attached my code and also the relevant file of it with this issue. Feel free to request additional details to assist in diagnosing the issue. Thank you for your support!
[Code.txt](https://github.com/do-mpc/do-mpc/files/13425562/Code.txt)
[data_frame_typical_heat_day_constant.csv](https://github.com/do-mpc/do-mpc/files/13425568/data_frame_typical_heat_day_constant.csv)

**Comment by Mrfeli01** [comment]
Hey AlirezaYaghoubi,
please show the relevant part of your code here in the comments so that I can take a look at it. Which version of do-mpc are you using?

Best 
Mrfeli01

**Comment by AlirezaYaghoubi** [comment]
Hey  Mrfeli01,

I appreciate your suggestion. Indeed, it is your entitlement, and the issue pertains to the solver and my equations. I have rectified my equations, and the problem has been resolved. Thank you for your assistance.
