### ISSUE TITLE
Documented infeasibility code is not working

### ISSUE THREAD

**Issue by nombel** [do-mpc/do-mpc#425]
Hello everyone,
I am currently developing an MPC based supervisor algorithm, that specifically checks for problem infeasibility. For that I want to retieve the MPC solution and compare it to the bounds, as it is stated in the documentation here:
https://www.do-mpc.com/en/v4.1.0/Debugging.html#which-constraints-are-violated

```
lb_bound_violation = mpc.opt_x_num.cat <= mpc.lb_opt_x
ub_bound_violation = mpc.opt_x_num.cat <= mpc.ub_opt_x
  
opt_labels = mpc.opt_x.labels()
labels_lb_viol =np.array(opt_labels)[np.where(lb_viol)[0]]
labels_ub_viol =np.array(opt_labels)[np.where(lb_viol)[0]]
```

this code simply does not work and throws the following error message:
```
Traceback (most recent call last):
  File "mpc.py", line 205, in <module>
    lb_bound_violation = mpc.opt_x_num.cat <= mpc.lb_opt_x
  File "path_omitted/python/3.8.10/lib/python3.8/site-packages/casadi/casadi.py", line 9047, in __le__
    def __le__(x, y): return _casadi.le(x, y)
RuntimeError: .../casadi/core/matrix_impl.hpp:1358: Dimension mismatch for (x<=y), x is 1176x1, while y is 0x0
```
I am not knowlegable enough to know how this could be fixed and would therefore be very grateful for any help. If there is another way to know wether or not the problem is infeasible please let me know

Kind Regards,
nombel

**Comment by Mrfeli01** [comment]
Dear nombel,

if you want to check all states of the optimization problems for constraint violations you can try the following code:

```
lb_violation = mpc.opt_x_num.cat <= mpc._lb_opt_x.cat
ub_violation = mpc.opt_x_num.cat >= mpc._ub_opt_x.cat

opt_labels = mpc.opt_x.labels()
labels_lb_viol = np.array(opt_labels)[np.where(lb_violation)[0]]
labels_ub_viol = np.array(opt_labels)[np.where(ub_violation)[0]]
```

The docs your link it pointing to are outdated.
Hope it helps!

Best
Mrfeli01
