### ISSUE TITLE
Unable to run do_mpc after installation 

### ISSUE THREAD

**Issue by kashifzr** [do-mpc/do-mpc#432]
Unable to run do_mpc after installation 

- Installation via pip

**Screenshots**

<pre>Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; import cryptography
&gt;&gt;&gt; import do_mpc
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/abc/.local/lib/python3.8/site-packages/do_mpc/__init__.py&quot;, line 86, in &lt;module&gt;
    import asyncua
  File &quot;/home/abc/.local/lib/python3.8/site-packages/asyncua/__init__.py&quot;, line 13, in &lt;module&gt;
    from .client import Client
  File &quot;/home/abc/.local/lib/python3.8/site-packages/asyncua/client/__init__.py&quot;, line 1, in &lt;module&gt;
    from .client import Client
  File &quot;/home/abc/.local/lib/python3.8/site-packages/asyncua/client/client.py&quot;, line 5, in &lt;module&gt;
    from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes
ModuleNotFoundError: No module named &apos;cryptography.hazmat.primitives.asymmetric.types&apos;
&gt;&gt;&gt; 
</pre>

OS - Ubuntu 20

**Additional context**

**Comment by Mrfeli01** [comment]
Hello kashifzr,
by using `pip install do-mpc` additional functions like the asyncua library, which is used for the opcua functions, are not installed. For more information please see [here](https://www.do-mpc.com/en/latest/installation.html). Try to install `asyncua `seperatly (`pip install asyncua`) to resolve your error.

Hope its helps!
Mrfeli01

**Comment by kashifzr** [comment]
@Mrfeli01 thanks for your reply
However when i run pip install do_mpc[full] it does install asyncua automatically 

Here is the screen shot 

<pre> pip install do_mpc[full]
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: do_mpc[full] in ./.local/lib/python3.8/site-packages (4.6.4)
Requirement already satisfied: casadi&gt;=3.6.0 in ./.local/lib/python3.8/site-packages (from do_mpc[full]) (3.6.4)
Requirement already satisfied: scipy in ./.local/lib/python3.8/site-packages (from do_mpc[full]) (1.10.1)
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from do_mpc[full]) (1.23.5)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from do_mpc[full]) (3.1.2)
Requirement already satisfied: onnx&gt;=1.13.0 in ./.local/lib/python3.8/site-packages (from do_mpc[full]) (1.14.1)
Requirement already satisfied: ipykernel in ./.local/lib/python3.8/site-packages (from do_mpc[full]) (6.27.0)
Requirement already satisfied: packaging in ./.local/lib/python3.8/site-packages (from do_mpc[full]) (23.1)
Collecting asyncua (from do_mpc[full])
  Downloading asyncua-1.0.5-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: protobuf&gt;=3.20.2 in ./.local/lib/python3.8/site-packages (from onnx&gt;=1.13.0-&gt;do_mpc[full]) (3.20.3)
Requirement already satisfied: typing-extensions&gt;=3.6.2.1 in ./.local/lib/python3.8/site-packages (from onnx&gt;=1.13.0-&gt;do_mpc[full]) (4.8.0)
Requirement already satisfied: aiofiles in ./.local/lib/python3.8/site-packages (from asyncua-&gt;do_mpc[full]) (23.2.1)
Requirement already satisfied: aiosqlite in ./.local/lib/python3.8/site-packages (from asyncua-&gt;do_mpc[full]) (0.19.0)
Requirement already satisfied: python-dateutil in ./.local/lib/python3.8/site-packages (from asyncua-&gt;do_mpc[full]) (2.8.2)
Requirement already satisfied: pytz in ./.local/lib/python3.8/site-packages (from asyncua-&gt;do_mpc[full]) (2023.3.post1)
Requirement already satisfied: cryptography in ./.local/lib/python3.8/site-packages (from asyncua-&gt;do_mpc[full]) (3.4)
Requirement already satisfied: sortedcontainers in ./.local/lib/python3.8/site-packages (from asyncua-&gt;do_mpc[full]) (2.4.0)
Requirement already satisfied: pyOpenSSL in /usr/lib/python3/dist-packages (from asyncua-&gt;do_mpc[full]) (19.0.0)
Requirement already satisfied: comm&gt;=0.1.1 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (0.2.0)
Requirement already satisfied: debugpy&gt;=1.6.5 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (1.8.0)
Requirement already satisfied: ipython&gt;=7.23.1 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (8.12.3)
Requirement already satisfied: jupyter-client&gt;=6.1.12 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,&gt;=4.12 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (5.5.0)
Requirement already satisfied: matplotlib-inline&gt;=0.1 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (0.1.6)
Requirement already satisfied: nest-asyncio in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (1.5.8)
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from ipykernel-&gt;do_mpc[full]) (5.5.1)
Requirement already satisfied: pyzmq&gt;=20 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (25.1.1)
Requirement already satisfied: tornado&gt;=6.1 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (6.3.3)
Requirement already satisfied: traitlets&gt;=5.4.0 in ./.local/lib/python3.8/site-packages (from ipykernel-&gt;do_mpc[full]) (5.13.0)
Requirement already satisfied: backcall in ./.local/lib/python3.8/site-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.2.0)
Requirement already satisfied: decorator in /usr/lib/python3/dist-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (4.4.2)
Requirement already satisfied: jedi&gt;=0.16 in ./.local/lib/python3.8/site-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.19.1)
Requirement already satisfied: pickleshare in ./.local/lib/python3.8/site-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,&lt;3.1.0,&gt;=3.0.30 in ./.local/lib/python3.8/site-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (3.0.41)
Requirement already satisfied: pygments&gt;=2.4.0 in ./.local/lib/python3.8/site-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (2.17.2)
Requirement already satisfied: stack-data in ./.local/lib/python3.8/site-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.6.3)
Requirement already satisfied: pexpect&gt;4.3 in ./.local/lib/python3.8/site-packages (from ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (4.8.0)
Requirement already satisfied: importlib-metadata&gt;=4.8.3 in ./.local/lib/python3.8/site-packages (from jupyter-client&gt;=6.1.12-&gt;ipykernel-&gt;do_mpc[full]) (6.8.0)
Requirement already satisfied: platformdirs&gt;=2.5 in ./.local/lib/python3.8/site-packages (from jupyter-core!=5.0.*,&gt;=4.12-&gt;ipykernel-&gt;do_mpc[full]) (4.0.0)
Requirement already satisfied: six&gt;=1.5 in ./.local/lib/python3.8/site-packages (from python-dateutil-&gt;asyncua-&gt;do_mpc[full]) (1.15.0)
Requirement already satisfied: cffi&gt;=1.12 in ./.local/lib/python3.8/site-packages (from cryptography-&gt;asyncua-&gt;do_mpc[full]) (1.16.0)
Requirement already satisfied: setuptools-rust&gt;=0.11.4 in ./.local/lib/python3.8/site-packages (from cryptography-&gt;asyncua-&gt;do_mpc[full]) (1.8.1)
Requirement already satisfied: pycparser in ./.local/lib/python3.8/site-packages (from cffi&gt;=1.12-&gt;cryptography-&gt;asyncua-&gt;do_mpc[full]) (2.21)
Requirement already satisfied: zipp&gt;=0.5 in ./.local/lib/python3.8/site-packages (from importlib-metadata&gt;=4.8.3-&gt;jupyter-client&gt;=6.1.12-&gt;ipykernel-&gt;do_mpc[full]) (3.17.0)
Requirement already satisfied: parso&lt;0.9.0,&gt;=0.8.3 in ./.local/lib/python3.8/site-packages (from jedi&gt;=0.16-&gt;ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.8.3)
Requirement already satisfied: ptyprocess&gt;=0.5 in ./.local/lib/python3.8/site-packages (from pexpect&gt;4.3-&gt;ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.7.0)
Requirement already satisfied: wcwidth in /usr/lib/python3/dist-packages (from prompt-toolkit!=3.0.37,&lt;3.1.0,&gt;=3.0.30-&gt;ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.1.8)
Requirement already satisfied: setuptools&gt;=62.4 in ./.local/lib/python3.8/site-packages (from setuptools-rust&gt;=0.11.4-&gt;cryptography-&gt;asyncua-&gt;do_mpc[full]) (68.2.2)
Requirement already satisfied: semantic-version&lt;3,&gt;=2.8.2 in ./.local/lib/python3.8/site-packages (from setuptools-rust&gt;=0.11.4-&gt;cryptography-&gt;asyncua-&gt;do_mpc[full]) (2.10.0)
Requirement already satisfied: tomli&gt;=1.2.1 in ./.local/lib/python3.8/site-packages (from setuptools-rust&gt;=0.11.4-&gt;cryptography-&gt;asyncua-&gt;do_mpc[full]) (2.0.1)
Requirement already satisfied: executing&gt;=1.2.0 in ./.local/lib/python3.8/site-packages (from stack-data-&gt;ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (2.0.1)
Requirement already satisfied: asttokens&gt;=2.1.0 in ./.local/lib/python3.8/site-packages (from stack-data-&gt;ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (2.4.1)
Requirement already satisfied: pure-eval in ./.local/lib/python3.8/site-packages (from stack-data-&gt;ipython&gt;=7.23.1-&gt;ipykernel-&gt;do_mpc[full]) (0.2.2)
Downloading asyncua-1.0.5-py3-none-any.whl (772 kB)
   <font color="#729C1F">━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</font> <font color="#4E9A06">772.3/772.3 kB</font> <font color="#CC0000">11.9 MB/s</font> eta <font color="#06989A">0:00:00</font>
Installing collected packages: asyncua
Successfully installed asyncua-1.0.5
</pre>

When use do_mpc then issue 

Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import do_mpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abc/.local/lib/python3.8/site-packages/do_mpc/__init__.py", line 86, in <module>
    import asyncua
  File "/home/abc/.local/lib/python3.8/site-packages/asyncua/__init__.py", line 13, in <module>
    from .client import Client
  File "/home/abc/.local/lib/python3.8/site-packages/asyncua/client/__init__.py", line 1, in <module>
    from .client import Client
  File "/home/abc/.local/lib/python3.8/site-packages/asyncua/client/client.py", line 5, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes
ModuleNotFoundError: No module named 'cryptography.hazmat.primitives.asymmetric.types'

Even When I try pip install asyncua even then its install same asyncua which is already installed with do_mpc, But cryptography do not support this 


<pre>pip show asyncua
Name: asyncua
Version: 1.0.5
Summary: Pure Python OPC-UA client and server library
Home-page: http://freeopcua.github.io/
Author: Olivier Roulet-Dubonnet
Author-email: olivier.roulet@gmail.com
License: GNU Lesser General Public License v3 or later
Location: /home/abc/.local/lib/python3.8/site-packages
Requires: aiofiles, aiosqlite, cryptography, pyOpenSSL, python-dateutil, pytz, sortedcontainers, typing-extensions
Required-by: 
</pre>

**Comment by Mrfeli01** [comment]
Hello kashifzr,

can you please post the code that causes the error?

Best
Mrfeli01

**Comment by kashifzr** [comment]
@Mrfeli01 thanks for your reply 

How to run code without installation. I am just trying to install do_mpc, then i found this issue which is when run pip install do_mpc it install required asyncua automatically. As you use this package, can you share which version of cryptography is used in your systems. mine is 
<pre>pip show cryptography
Name: cryptography
Version: 3.4.5
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: https://github.com/pyca/cryptography
Author: The Python Cryptographic Authority and individual contributors
Author-email: cryptography-dev@python.org
License: BSD or Apache License, Version 2.0
Location: /home/abc/.local/lib/python3.8/site-packages
Requires: cffi
Required-by: asyncua
</pre>

I thinks its some how related to cryptography

**Comment by kashifzr** [comment]
By changing cryptography to 41.0.7 and installation of pyopenssl remove this issue 

 pip show cryptography
Name: cryptography
Version: 41.0.7
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: 
Author: 
Author-email: The Python Cryptographic Authority and individual contributors <cryptography-dev@python.org>
License: Apache-2.0 OR BSD-3-Clause
Location: /home/abc/.local/lib/python3.8/site-packages
Requires: cffi
Required-by: asyncua, pyOpenSSL
