### ISSUE TITLE
Improve Graphics Module

### ISSUE THREAD

**Issue by 4flixt** [do-mpc/do-mpc#48]
The current implementation of **do-mpc** graphics is rather slow and can be improved significantly. 
This is especially important when creating animations or monitoring results visually.

Currently, we clear all axes and redraw all lines when calling ``graphics.plot_results`` and ``graphics.plot_predictions``.

Alternatively, we should have all line object already created and just update their data. 

The following toy example shows the procedure and the difference in speed:

![image](https://user-images.githubusercontent.com/32864011/77431851-939d9700-6ddd-11ea-801b-e6073c3b2358.png)

We can expect a 30x speed increase!

**Comment by 4flixt** [comment]
to transfer the results from the snippet above to the ``graphics`` module, we need to create the ``line`` objects in some initialization phase and simply update their data when calling ``plot_results`` and ``plot_predictions``.

This requires some changes in the architecture, **because currently a ``graphics`` instance is not bound to a distinct data object.** In the contrary, it is defined with respect to the **do-mpc** model (and its variables) and can then be used to plot data from the simulator, estimator, controller etc (all of them in the same plot, if desired).

Creating the empty line objects during a setup phase requires individual lines for individual **do-mpc** modules. 
I suggest to bind instances of the graphics class to instances of the data class. This has the downside that in some cases very similar plots are going to be configured for multiple data objects (e.g. simulator and MPC).

**Comment by alexandru-tc** [comment]
Thanks for the update. Great to see the tremendous speed increase!
However, if I understand the implementation correctly, the data line can be
created during initialization, without having to bind it to any actual
data. We can, later on, dump any data we want plotted into the respective
container/artist. At any call to plot_results() the data source can change.
This would require to define a number of possible (maximum) data sources
per each axis. When calling plot_results, we can dump data from any
module.data into the line and call plot.show(). But I would have to try it
out to see if it actually works like that. Would we ever have more than,
say 3 sources per plot? 3=1 simulator+1 controller + 1 estimator data.

**Comment by 4flixt** [comment]
What you are saying is correct, it doesnt have to be bound to a particular data object. We can plot with e.g. the MPC **OR** the simulator results by calling the ``line.set_data`` method. However, currently we are able to create and configure an instance of the graphics module and plot e.g. the MPC **AND** the simulator results on the same axes. If we feel like it we can also throw in the estimator lines.  To achieve the same with the new proposal, all lines for all data objects need to be initiated. Maybe we do not bind it to the data object but instead just require one instance per set of lines? If you want simulator+MPC in the same plot you need to obtain two instances (which could have an identical configuration).

**Comment by alexandru-tc** [comment]
Actually, I've just tried it out and it appears that we do not have to initialize anything, we can instead add lines to the plot and everything will be sorted out in the background by matplotlib. SO I'm thinking we can keep the initialization the same, and would have to update the routines for add_line(), plot_results() and plot_predictions().  The procedure would look something like the following:

ax = fig.axes    # returns list of all available axes
....
# anywhere in the routines
new_line = module.data._x #could be any data source
ax[i].add_artist(new_line) # this also automatically updates the plot
...
# whenever the data changes
new_line.set_data(new_data) #this also updates the plot 
...

Is this what you were thinking of? Maybe we should think of customizing the number of artists for each axis. E.g. when adding lines, asking the user what kind of line that will be (simulator, estimator, controller -history or future predictions) etc

I think it is very flexible.

**Comment by 4flixt** [comment]
I've been working on this issue in the past couple of days and will soon push new results. The new approach is based on updating the data on existing lines (as discussed above).

In practice I achieve 4x times faster performance when creating the plot. Exporting a GIF was, however, still very slow and I realized that it also has a lot to do with ImageMagick (at least in my case). The bottleneck was the default memory limit of ImageMagick.

This [block post](https://blog.bigbinary.com/2018/09/12/configuring-memory-allocation-in-imagemagick.html) helped me a lot and now exporting GIFs is much faster.

**Comment by 4flixt** [comment]
Quickly wrapping up the changes:

1. The `Graphics` class is now initiated with an `Data` object:    https://github.com/do-mpc/do-mpc/blob/89adb6826b12f88bc78ba137fee3cdb79ec96a00/do_mpc/graphics.py#L103

2. The `Graphics` class has two new properties `result_lines` and  `pred_lines`. These are structures that hold all the Matplotlib lines within the class.

3. `add_line` now adds new line object(s) to these structures: https://github.com/do-mpc/do-mpc/blob/89adb6826b12f88bc78ba137fee3cdb79ec96a00/do_mpc/graphics.py#L265

4. When calling `plot_results` and /or `plot_predictions` these lines are getting updated: https://github.com/do-mpc/do-mpc/blob/89adb6826b12f88bc78ba137fee3cdb79ec96a00/do_mpc/graphics.py#L303

5. Configuring the style of lines is now really easy and customizable. See for example here: https://github.com/do-mpc/do-mpc/blob/89adb6826b12f88bc78ba137fee3cdb79ec96a00/examples/CSTR/main.py#L81

6. Retrieving lines by name is also useful for legends and other Matplotlib features: 
https://github.com/do-mpc/do-mpc/blob/89adb6826b12f88bc78ba137fee3cdb79ec96a00/examples/CSTR/main.py#L91

**Comment by alexandru-tc** [comment]
Thanks Felix for working on the graphics! I haven't had the chance to try them out yet, but I'm looking forward to that.  How do you suggest we proceed? 
I'm thinking about the following procedure. I would first merge the master into the realtime branch, when I have the OK from you, and try it locally. Meanwhile I will also update the docstrings and try out the documentation for the realtime modules. Finally you can merge my branch into the master. I would be very grateful if you could give it a quick try before. Or let's talk separately about that.

**Comment by 4flixt** [comment]
Completed with #50
