### ISSUE TITLE
Estimation strategies: new section in the documentation

### ISSUE THREAD

**Issue by alexandru-tc** [do-mpc/do-mpc#49]
This is firstly a question raised to @sergiolucia and @4flixt and subsequently a task tracking for myself. 
I believe the documentation on estimators could benefit from a more general introduction. This section should explain the possibilities offered and show snippets of code in a Jupyter notebook style.

I'm thinking to start with a visual depiction of the optimizer in the loop and explain the difference between state-feedback and output-feedback. The realization of the two possibilities should also be highlighted (I've implemented it in the CSTR example on the realtime branch).

Next, the three currently available estimators should be introduced. So far we have two, let's call them simple solutions, and one more complex solution. I would suggest to discuss the crude full state-feedback, as well as the EKF, on this general introduction page. I would go about it based on the CSTR example. As far as the MHE is concerned, it should be only mentioned and the reader should be directed to the already existing and very comprehensive section of the documentation.

I would be grateful to hear some quick impressions about the topic. I'll start preparing the docu and the notebook for it. I'll also drop samples in here as I go along.

**Comment by 4flixt** [comment]
Hey Alex, thank you for the proposal! I agree, we can absolutely improve on the documentation about estimators. Have you investigated the current [Getting started: MHE](https://www.do-mpc.com/en/latest/mhe_example.html) docu? I think that goes in the direction you are thinking? Maybe we can further improve that, as a first step?

**Comment by alexandru-tc** [comment]
I did not want to change the MHE notebook. As of now I'm implementing a new `Getting started: real-time MPC` notebook and I will add a section about using the EKF there, based on the polymerization reactor. I'm thinking we can add some more things about using the estimators and state/output-feedback in the general `Getting started: do-mpc` documentation, it seems more like the place for an overview.

**Comment by 4flixt** [comment]
Great thats awesome! Thanks alex :) 
However, I think I would try to not overload the getting_started notebooks. I was considering to add a new TOC element where we explain the theory (with some API and implementation remarks) on MHE, MPC and EKF?

**Comment by alexandru-tc** [comment]
I'm open for suggestions on that, sure! Now I have the notebook, but that content can be explained in other formats as well, because I did not intend for the notebook to be runnable anyway.

Should we have a discussion about how to best structure the documentation? Skype call or just here?

**Comment by 4flixt** [comment]
I added you on skype! I am available anytime :D

**Comment by alexandru-tc** [comment]
As it stands, Felix and I have agreed on the following two ideas:

1) The documentation will have 4 Jupyter notebooks: general MPC, getting started EKF, getting started MHE and, finally, getting started with real-time MPC.
2) The notebooks should be as brief as possible. Further on we have agreed to add a detailed section in the documentation which deals with in-depth technical and theoretical aspects. 
 
I will finish the real-time documentation my branch. The further changes will be made together, on a special branch.
