### ISSUE TITLE
MPC/MHE add new property "x0" (and "p0")

### ISSUE THREAD

**Issue by 4flixt** [do-mpc/do-mpc#55]
It is currently not clear to the user how to obtain the current initial state from the controller / estimator. These important properties should be more 
accessible to the user, by declaring them properties.

Furthermore, we can use the setter method to use the same properties to conveniently set the initial guess?

**Comment by alexandru-tc** [comment]
I agree with the idea and I was also thinking about the best way to do it while coding the EKF. Might I propose a small modification? 
I'm thinking to not mix initial state and current state/estimate. I'm thinking to call the initialization "x0" and to update it with the initialization function, while the current state/estimate to be called "xk" and have it as a property that can be accessed via something like 'mpc.xk' or via a getter function. I implemented something like this for the EKF.

**Comment by 4flixt** [comment]
Do you mean initial guess by initial state? Or just the very first initial state when creating the MHE/ MPC instance?

**Comment by alexandru-tc** [comment]
True, the language is slightly confusing between the estimator and controller...

I think 'x0' should just denote the very first initial state vector, no matter what module it refers to (sim, mpc, estimator). Then there will be something like 'x_init' or 'initial_guess', which could be a implemented as a property of the MPC and MHE denoting the current initial guess of the optimizer. Finally there will be an 'xk', which would be the current state and it makes most sense for the simulator and the estimators. For the state-feedback and EKF it's pretty straight forward. For the MHE I guess it would be the state at time `t_now` ?? Just a suggestion, don't want to influence your  MHE implementation :)

**Comment by 4flixt** [comment]
I really like to denote the current state as xk but I am not sure if we require a dedicated property x0? But lets discuss this tomorrow :) Other than that I think I would continue calling the optimizer initial guess opt_x_0 or somthing like it. I want to make sure that we are neither confusing ourselves nor others with the generic variable x used in optimization (here opt_x) and the state vector x.
