### ISSUE TITLE
CSTR Example - TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by MinWu2018** [do-mpc/do-mpc#61]
When running the CSTR example, initialize graphic:
`graphics = do_mpc.graphics.Graphics(mpc.data)`
it came 
`TypeError: __init__() takes 1 positional argument but 2 were given`
May I ask how to fix this problem?

**Comment by 4flixt** [comment]
Hi MinWu,

can you quickly give me some details which do-mpc version you have installed (did you use pip or just clone the must current master?). And how did you obtain the examples?

Best,
Felix

**Comment by MinWu2018** [comment]
Hello,
I installed 
```
do-mpc                     4.0.0b1
casadi                        3.5.1
```
and I used pip. The examples were cloned from Github.

Thanks.

**Comment by 4flixt** [comment]
Ok so the examples are created for a newer version of do-mpc and wont work in your current setup. You can either: 
- Update do-mpc to version 4.0.0b3
- Get the previous version of the examples from the assets of [release 4.0.0b1](https://github.com/do-mpc/do-mpc/releases/tag/v4.0.0-beta1)

**Comment by 4flixt** [comment]
Thank you for your issue MinWu. As a response to this confusion I have created #62 .

**Comment by MinWu2018** [comment]
Thank you very much for your help, @4flixt.
