### ISSUE TITLE
Control horizon

### ISSUE THREAD

**Issue by amabilis-ribeiro** [do-mpc/do-mpc#75]
Hello,

I would like to know what the control horizon is. Is it the same as the prediction horizon? Is it fixed? 

It would be nice if we could set the control horizon as well in mpc.set_param. 

Thank you.

**Comment by 4flixt** [comment]
Hi Amabilis-Ribeiro,

when I first learned about MPC I was also taught the difference between control and prediction horizon but from my experience that is somewhat outdated. **do-mpc** is implemented with only the control horizon in mind: The optimizer is choosing an input for every step within this horizon. In that sense you could say control horizon = prediction horizon. In most cases, this will lead to significantly better performance and should only lead to a moderate increase of computational complexity. 
I hope this answers your question!

Best,
Felix

**Comment by amabilis-ribeiro** [comment]
Hello Felix, 

Thank you very much for your speedy reply! 

Best regards, 

Milena

**Comment by 4flixt** [comment]
You are welcome!
