### ISSUE TITLE
Documentation: Use of deprecated functions

### ISSUE THREAD

**Issue by Guillaume-Duc-95** [do-mpc/do-mpc#76]
Regarding the documentation on our [do-mpc](do-mpc.com) homepage.

**Link to page / section of the issue** 
https://www.do-mpc.com/en/latest/getting_started.html

**What is wrong / missing?**
In cell 51, the tutorial call 2 deprecated methods:
https://github.com/do-mpc/do-mpc/blob/8e1e3539b40bb5b546e1bd251896ac34efcbdff5/documentation/source/getting_started.ipynb#L1459-L1460

**How could it be improved / what should be added?**
Should we replace them with the "reset_history" method ?

**Comment by 4flixt** [comment]
Thank you for the feedback! That is indeed an error and will be fixed with the next release.

**Comment by 4flixt** [comment]
sorry i just now saw your merge request!
