### ISSUE TITLE
[MPC/MHE] Let users choose wether nl_cons is active once per FE or at each collocation point

### ISSUE THREAD

**Issue by 4flixt** [do-mpc/do-mpc#78]
Currently nl_cons is checking the nonlinear constraints (for MPC and MHE) only at the beginning of the FE. This is often sufficient but sometimes it might be necessary to check the constraints for all collocation points.

**Comment by sergiolucia** [comment]
In my opinion, the standard should be that both nl_cons and the standard bounds are checked on all collocation points

**Comment by 4flixt** [comment]
Yes that would be better! But I like the option to switch.
For some problems one can safe a lot of computation time and obtain almost the same results when checking only at the FE borders.
