### ISSUE TITLE
Time varying parameter in the terminal cost

### ISSUE THREAD

**Issue by Guillaume-Duc-95** [do-mpc/do-mpc#81]
**Is your feature request related to a problem? Please describe.**
I would like to implement a mpc controller with the following objective function:
<img src="https://render.githubusercontent.com/render/math?math=F(x, x_s) := \sum_{k=0}^{N-1} (x_k-x_{sk})'Q(x_k-x_{sk})%2B(x_N-x_{sN})'Q_N(x_N-x_{sN})">

with x_s some time varying parameters. The function "set_tvp_function" of the MPC class allows to set their value for the N horizon steps.  However this function does not seem to set the value for the terminal cost. Is there a way to set it ?

**Comment by 4flixt** [comment]
I noticed the other day that this would be useful. It is a minor change in the code and should be done soon. You can fix it if you like or I'll do it on monday :)
