### ISSUE TITLE
Error evaluating Jacobian of equality constraints at user provided starting point.   No scaling factors for equality constraints computed!

### ISSUE THREAD

**Issue by DystopianLphant** [do-mpc/do-mpc#91]
**Describe the bug**
I'm getting the same error as [this](https://github.com/do-mpc/do-mpc/issues/26). I'm trying to build an mpc for a special kind of aeroplane using the general motion equations. 

The problem is most likely related to the way initial conditions are set.
Right now I'm following [this example](https://www.do-mpc.com/en/latest/getting_started.html#Objective-function) by creating a vector x0 that contains all the initial state values to be passed to the control loop.

The problem is that setting some states to a value implies automatically the values of many other states. So the expected behaviour would be setting some states to a values, le the model compute the others fot t0 and then feeding them to the simulation-control loop. 

The problem came up when I added a convoluted expression for the control surface in addition to the engine. I'm now trying to simplify the model to see it this is the main problem.
 

**Which version of do-mpc are using and how did you obtain it?**
Installation via pip, 4.1.0

**Which system are you working on?**
- Linux

**Comment by 4flixt** [comment]
Hi DystopianLphant,

what exactly do you mean by 

> The problem is that setting some states to a value implies automatically the values of many other states. So the expected behaviour would be setting some states to a values, le the model compute the others fot t0 and then feeding them to the simulation-control loop.

How are the states related to each other? Do you have algebraic equations? Otherwise it should be possible to set all states independently (within physically sane bounds).

**Comment by 4flixt** [comment]
Regardless of what I wrote above: This error typically appears if you have expressions in the model such as:

- 1/x
- ln(x)

for example in the right-hand-side of the ODE or the objective function **and** if your initial guess is then x=0.  Make sure that you set an intial state (and input) for the MPC controller and then invoke ``mpc.set_intial_guess()``.

**Comment by DystopianLphant** [comment]
> Hi DystopianLphant,
> 
> what exactly do you mean by
> 
> > The problem is that setting some states to a value implies automatically the values of many other states. So the expected behaviour would be setting some states to a values, le the model compute the others fot t0 and then feeding them to the simulation-control loop.
> 
> How are the states related to each other? Do you have algebraic equations? Otherwise it should be possible to set all states independently (within physically sane bounds).
I have 2 vectors representing velocities in two different frames and 3 angles that describe such rotation. Once the angles and one of the velocities are defined the other vector is (almost always) univocally defined.

Before adding the new contr inputs (that have extremely convoluted expression that mix casadi and numpi) it was working, so the state expressions don't seem to be the problem.

Anyway, I'm defining the reference value in the lterm function as (state - desired_steady_state_value)^2, just for confirmation on the method

**Comment by 4flixt** [comment]
If you have the same states in multiple frames you should really only define them once as states and use e.g. ``set_expression`` to have their representation in another frame.

**Comment by DystopianLphant** [comment]
the problem is related to the way I'm managing some forces. I'm defining np.array components using some states, this is what creates the problem. I thought that since it wasn't returning error maybe it worked, but apparently not. I think this problem belongs somewhere else then. thank you for your help

**Comment by 4flixt** [comment]
ok! Hope you'll figure it out! I am closing this issue now. Feel free to ask again, if you have another problem :)

**Comment by DystopianLphant** [comment]
well, if you could point me to some documentation that could solve my problem I would be glad. I basically have a matrix made of real number that has to be multiplied by a vector containing the instantaneous value of the some state variable in the form [x**2 x 1] in order to compute a force. I have used np.array([x**2, x,1]) and different product types from casadi and numpi. sorry if I'm pedant but maybe you know a direction I could move to
