### ISSUE TITLE
Syntax error on import

### ISSUE THREAD

**Issue by rupumped** [do-mpc/do-mpc#97]
The line `import do_mpc` results in a syntax error:

`import do_mpc`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/[USER]/.local/lib/python2.7/site-packages/do_mpc/__init__.py", line 25, in <module>
    import do_mpc.controller
  File "/home/[USER]/.local/lib/python2.7/site-packages/do_mpc/controller.py", line 1068
    obj += self.rterm_factor.cat.T@((opt_x['_u', 0, s]-opt_p['_u_prev']/self._u_scaling)**2)
                                  ^
SyntaxError: invalid syntax
```

This is a fresh pip install on Ubuntu 18.04.

**Comment by 4flixt** [comment]
Hi,

Thank your for pointing out this error.
It is indeed unexpected. We will look into it.

Best
4flixt

**Comment by 4flixt** [comment]
Ok I reread the error. Looks like you are using python 2.7 which isn't supported. Could you try again with Python 3?
I'll raise an issue to add a warning if users try to work with python 2.

Best
4flixt
