### ISSUE TITLE
time varying parameters from files

### ISSUE THREAD

**Issue by P11GH** [do-mpc/do-mpc#99]
Hi,
I am trying to set the time varying parameter (external temperature in my case) to be from a csv file, but I cannot obtain the correct results. When I set the tvp as a number like the example in the documentation, it works well. But when I changed to be from a file, it can run but the results are not correct and the input are always set to be its upper bound. What will be the problem?

Part of the code is shown below
![image](https://user-images.githubusercontent.com/50893243/102392953-999b5f80-3f8c-11eb-8b9b-165a556bfd9f.png)

**Comment by 4flixt** [comment]
Hi P11GH,

thank you for your question. When you say you are trying to set the tvp values from a csv file, do you mean you load the csv once, keep it in memory and pass the respective row at each time-step? That shouldn't be any different than obtaining an array of data from any other source. Maybe check if it has the right format?

I can't really comment on the screenshot above. I don't see any obvious errors. 

Best
4flixt

**Comment by P11GH** [comment]
Hi $flixt,
Thank you very much. The code has no bug and can run, but the results are not correct. My questions is that whether the way I set the tvp values are correct. I first load the csv file to a numpy array, and pass the whole array, which is Tout_all in the first line in the picture, to the MPC. Then at each step, I set a slice of Tou_all as the tvp. Is this the recommended way set tvp from a csv file? 
Best,
Peng

**Comment by P11GH** [comment]
> Hi P11GH,
> 
> thank you for your question. When you say you are trying to set the tvp values from a csv file, do you mean you load the csv once, keep it in memory and pass the respective row at each time-step? That shouldn't be any different than obtaining an array of data from any other source. Maybe check if it has the right format?
> 
> I can't really comment on the screenshot above. I don't see any obvious errors.
> 
> Best
> 4flixt

**Comment by P11GH** [comment]
Hi 4flixt,
In the FAQ part of do-mpc website, it uses external temperature as an example for tvp. Could you also create code for such an example? So I can learn how to set tvp from files.
Best,
P11GH
